/*
 *
 *    Copyright (c) 2021 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <app/data-model/DecodableList.h>
#include <app/data-model/Decode.h>
#include <app/data-model/Encode.h>
#include <app/data-model/List.h>
#include <app/util/basic-types.h>

namespace chip {
namespace app {
namespace clusters {

namespace AccountLoginCluster {
constexpr ClusterId kClusterId = 0x050E;

}
namespace AdministratorCommissioningCluster {
constexpr ClusterId kClusterId = 0x003C;

}
namespace ApplicationBasicCluster {
constexpr ClusterId kClusterId = 0x050D;

}
namespace ApplicationLauncherCluster {
constexpr ClusterId kClusterId = 0x050C;

}
namespace AudioOutputCluster {
constexpr ClusterId kClusterId = 0x050B;

}
namespace BasicCluster {
constexpr ClusterId kClusterId = 0x0028;

}
namespace BindingCluster {
constexpr ClusterId kClusterId = 0xF000;

}
namespace ContentLauncherCluster {
constexpr ClusterId kClusterId = 0x050A;

}
namespace DiagnosticLogsCluster {
constexpr ClusterId kClusterId = 0x0032;

}
namespace GeneralCommissioningCluster {
constexpr ClusterId kClusterId = 0x0030;

}
namespace KeypadInputCluster {
constexpr ClusterId kClusterId = 0x0509;

}
namespace LevelControlCluster {
constexpr ClusterId kClusterId = 0x0008;

}
namespace LowPowerCluster {
constexpr ClusterId kClusterId = 0x0508;

}
namespace MediaInputCluster {
constexpr ClusterId kClusterId = 0x0507;

}
namespace MediaPlaybackCluster {
constexpr ClusterId kClusterId = 0x0506;

}
namespace NetworkCommissioningCluster {
constexpr ClusterId kClusterId = 0x0031;

}
namespace OtaSoftwareUpdateProviderCluster {
constexpr ClusterId kClusterId = 0x0029;

}
namespace OnOffCluster {
constexpr ClusterId kClusterId = 0x0006;

}
namespace OperationalCredentialsCluster {
constexpr ClusterId kClusterId = 0x003E;

}
namespace TvChannelCluster {
constexpr ClusterId kClusterId = 0x0504;

}
namespace TargetNavigatorCluster {
constexpr ClusterId kClusterId = 0x0505;

}
}
} // namespace clusters
} // namespace app
} // namespace chip
